/**
 * Topic-policy storage.
 *
 * One policy document per deployment (global). Persisted in Redis
 * under `orb2:policy:topics`. Rules let the operator declare topics
 * the agent should refuse to discuss (deny_list) or topics it should
 * exclusively discuss (allow_list); the agent loop is never modified
 * — instead, a system-prompt rider is generated by `evaluate.ts` and
 * concatenated into the chat handler's existing extras.
 */
import type { Store } from '../store/store.js'

export type TopicMode = 'off' | 'deny_list' | 'allow_list'
export type TopicClassifier = 'keyword' | 'hybrid' | 'llm'

export type TopicRule = {
  id: string
  topic: string
  description?: string
  patterns: string[]
  examples?: string[]
  enabled: boolean
}

export type TopicPolicy = {
  version: number
  mode: TopicMode
  classifier: TopicClassifier
  llm_model?: string
  rider_template: string
  rules: TopicRule[]
  updatedAt: string
  updatedBy?: string
}

const KEY = 'orb2:policy:topics'
const TTL_SECONDS = 86_400 * 365

const DEFAULT_DENY_TEMPLATE =
  'TOPIC POLICY: The operator of this Orb2 deployment has restricted you from discussing the following topics:\n' +
  '{{topics}}\n' +
  'If the user asks about any of them, briefly explain you cannot help with that topic in this deployment and offer to help with anything else in scope. Be concise, do not lecture, do not moralize.'

const DEFAULT_ALLOW_TEMPLATE =
  'TOPIC POLICY: The operator of this Orb2 deployment has restricted you to ONLY discuss the following topics:\n' +
  '{{topics}}\n' +
  'For any request outside this scope, briefly explain you can only help within those topics in this deployment. Be concise, do not lecture, do not moralize.'

export function defaultPolicy(): TopicPolicy {
  return {
    version: 1,
    mode: 'off',
    classifier: 'hybrid',
    rider_template: DEFAULT_DENY_TEMPLATE,
    rules: [],
    updatedAt: new Date().toISOString(),
  }
}

export function pickDefaultRiderForMode(mode: TopicMode): string {
  return mode === 'allow_list' ? DEFAULT_ALLOW_TEMPLATE : DEFAULT_DENY_TEMPLATE
}

function genRuleId(): string {
  const bytes = new Uint8Array(8)
  crypto.getRandomValues(bytes)
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('')
}

function sanitizeRule(r: Partial<TopicRule>, idHint?: string): TopicRule {
  const topic = String(r.topic || '').trim()
  if (!topic) throw new Error('rule.topic is required')
  const patterns = Array.isArray(r.patterns) ? r.patterns.filter(p => typeof p === 'string' && p.trim()).map(p => p.trim()) : []
  const examples = Array.isArray(r.examples) ? r.examples.filter(e => typeof e === 'string' && e.trim()).map(e => e.trim()) : undefined
  return {
    id: (idHint || r.id || genRuleId()).slice(0, 32),
    topic,
    description: typeof r.description === 'string' ? r.description : undefined,
    patterns,
    examples: examples && examples.length ? examples : undefined,
    enabled: r.enabled === false ? false : true,
  }
}

function isMode(v: unknown): v is TopicMode {
  return v === 'off' || v === 'deny_list' || v === 'allow_list'
}

function isClassifier(v: unknown): v is TopicClassifier {
  return v === 'keyword' || v === 'hybrid' || v === 'llm'
}

export function sanitizePolicy(input: Partial<TopicPolicy>, previous: TopicPolicy): TopicPolicy {
  const mode: TopicMode = isMode(input.mode) ? input.mode : previous.mode
  const classifier: TopicClassifier = isClassifier(input.classifier) ? input.classifier : previous.classifier
  const llm_model = typeof input.llm_model === 'string' && input.llm_model.trim() ? input.llm_model.trim() : undefined
  const rider_template =
    typeof input.rider_template === 'string' && input.rider_template.includes('{{topics}}')
      ? input.rider_template
      : previous.rider_template || pickDefaultRiderForMode(mode)
  const rules = Array.isArray(input.rules)
    ? input.rules.map(r => sanitizeRule(r))
    : previous.rules
  return {
    version: previous.version + 1,
    mode,
    classifier,
    ...(llm_model && { llm_model }),
    rider_template,
    rules,
    updatedAt: new Date().toISOString(),
  }
}

export async function loadPolicy(store: Store): Promise<TopicPolicy> {
  const raw = await store.getKv(KEY)
  if (!raw) return defaultPolicy()
  try {
    const parsed = JSON.parse(raw) as TopicPolicy
    if (!parsed || typeof parsed !== 'object') return defaultPolicy()
    return {
      ...defaultPolicy(),
      ...parsed,
      rules: Array.isArray(parsed.rules) ? parsed.rules : [],
    }
  } catch {
    return defaultPolicy()
  }
}

export async function savePolicy(store: Store, policy: TopicPolicy, updatedBy?: string): Promise<TopicPolicy> {
  const persisted: TopicPolicy = {
    ...policy,
    updatedAt: new Date().toISOString(),
    ...(updatedBy && { updatedBy }),
  }
  await store.putKv(KEY, JSON.stringify(persisted), TTL_SECONDS)
  return persisted
}

export async function addRule(store: Store, partial: Partial<TopicRule>, updatedBy?: string): Promise<TopicPolicy> {
  const current = await loadPolicy(store)
  const rule = sanitizeRule(partial)
  const next = sanitizePolicy({ ...current, rules: [...current.rules, rule] }, current)
  return savePolicy(store, next, updatedBy)
}

export async function patchRule(
  store: Store,
  id: string,
  partial: Partial<TopicRule>,
  updatedBy?: string,
): Promise<TopicPolicy | null> {
  const current = await loadPolicy(store)
  const idx = current.rules.findIndex(r => r.id === id)
  if (idx < 0) return null
  const merged = { ...current.rules[idx], ...partial, id }
  const sanitized = sanitizeRule(merged, id)
  const rules = current.rules.slice()
  rules[idx] = sanitized
  const next = sanitizePolicy({ ...current, rules }, current)
  return savePolicy(store, next, updatedBy)
}

export async function deleteRule(store: Store, id: string, updatedBy?: string): Promise<TopicPolicy | null> {
  const current = await loadPolicy(store)
  const filtered = current.rules.filter(r => r.id !== id)
  if (filtered.length === current.rules.length) return null
  const next = sanitizePolicy({ ...current, rules: filtered }, current)
  return savePolicy(store, next, updatedBy)
}
