FROM oven/bun:latest AS builder
WORKDIR /app
COPY package.json ./
RUN bun install --production
COPY src/ src/
COPY tsconfig.json ./

FROM oven/bun:latest
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/src ./src
COPY --from=builder /app/package.json ./
EXPOSE 50051 8080
ENV NODE_ENV=production
CMD ["bun", "run", "src/entrypoints/grpc.ts"]
