import { chromium } from 'playwright';
const b = await chromium.launch();
const page = await (await b.newContext()).newPage();
await page.context().addCookies([{ name: 'orb2_session', value: process.env.ORB_SESSION, domain: 'localhost', path: '/' }]);
await page.goto('http://localhost:9080/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
const S = process.env.SHOTS_DIR || '.';
const step = async () => (await page.locator('#firstrun-card .fr-words').textContent().catch(() => '')) || '';
console.log('step1:', (await step()).slice(0, 50));
await page.screenshot({ path: S + '/firstrun-1-name.png' });
await page.locator('#firstrun-card .fr-input').fill('Orb');
await page.locator('#firstrun-card .fr-btn:not(.ghost):not(.link)').click();
await page.waitForTimeout(1200);
console.log('step2:', (await step()).slice(0, 50));
await page.screenshot({ path: S + '/firstrun-2-members.png' });
await page.locator('#firstrun-card .fr-btn:not(.ghost):not(.link)').last().click();
await page.waitForTimeout(1500);
console.log('step3:', (await step()).slice(0, 50));
const devices = await page.locator('#firstrun-card .fr-row').allTextContents();
console.log('devices:', devices.join(' | ').slice(0, 200));
await page.screenshot({ path: S + '/firstrun-3-devices.png' });
await page.locator('#firstrun-card .fr-btn:not(.ghost):not(.link)').click();
await page.waitForTimeout(1200);
const gone = (await page.locator('#firstrun-card').count()) === 0;
console.log('finished, card gone:', gone);
await b.close();
process.exit(gone ? 0 : 1);
