"""
rak00n GPU neural TTS service — pluggable engine.

  RAK00N_TTS_ENGINE=kokoro   (default) Kokoro-82M: fast, clean, stable.
  RAK00N_TTS_ENGINE=orpheus  Orpheus-3B: emotive, conversational delivery and
                           honours inline cues like <laugh> <sigh> <chuckle>
                           <gasp> for real personality. Heavier but still small
                           enough to sit beside the cascade brain. Implemented
                           with plain transformers + SNAC — no vLLM, so none of
                           the multi-process instability that bit us elsewhere.

Both stream raw PCM16LE mono @ 24 kHz, so the browser and the voice backend
treat them identically. Audio is streamed as it's produced so the first words
reach the user while the rest is still synthesizing (keeps barge-in snappy).

Contract (consumed by src/api/voice/whisperBackend.ts):

  GET  /health   -> {"ok": true, "engine": "...", "sample_rate": 24000,
                     "device": "cuda", "voice": "..."}
  POST /tts      -> streamed raw PCM16LE mono bytes
       body: {"text": "...", "voice": "<engine voice>", "speed": 1.0}
       resp header: X-Sample-Rate: 24000
"""
from __future__ import annotations

import os
import re
import json
import logging
import urllib.request

import numpy as np
import torch
from fastapi import FastAPI
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("tts")

SAMPLE_RATE = 24000  # both engines emit 24 kHz
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
ENGINE = os.environ.get("RAK00N_TTS_ENGINE", "kokoro").lower()
LANG_CODE = os.environ.get("RAK00N_TTS_LANG", "a")  # Kokoro: 'a' = American English

# Default voice per engine. Kokoro: af_heart. Orpheus: tara (its best voice).
DEFAULT_VOICE = os.environ.get(
    "RAK00N_TTS_VOICE", "tara" if ENGINE == "orpheus" else "af_heart"
)
# Orpheus audio tokens are generated by a llama.cpp server (Q4_K_M GGUF, ~85
# tok/s on the GB10 — the only runtime/precision that clears realtime). This
# service consumes that token stream and decodes it to PCM with SNAC.
ORPHEUS_URL = os.environ.get("RAK00N_ORPHEUS_URL", "http://orpheus-llama:8081").rstrip("/")
ORPHEUS_MAX_TOKENS = int(os.environ.get("RAK00N_ORPHEUS_MAX_TOKENS", "1200"))

# Delivery cues the model may emit. Orpheus speaks them as nonverbal sounds;
# Kokoro can't, so for Kokoro we strip them before synthesis.
_CUE_RE = re.compile(r"<\s*(laugh|laughs|chuckle|sigh|sighs|gasp|groan|yawn|sniffle|cough)\s*>", re.I)

app = FastAPI(title="rak00n-tts", version="2.0")
_engine = ENGINE
_kokoro = None
_snac_model = None  # SNAC decoder (audio codes → waveform)


# ───────────────────────────── Kokoro ─────────────────────────────

def kokoro_pipeline():
    global _kokoro
    if _kokoro is None:
        from kokoro import KPipeline
        log.info("loading Kokoro pipeline on %s (lang=%s)", DEVICE, LANG_CODE)
        _kokoro = KPipeline(lang_code=LANG_CODE, device=DEVICE)
        log.info("Kokoro ready")
    return _kokoro


def kokoro_stream(text: str, voice: str, speed: float):
    # Kokoro can't voice nonverbal cues — drop them so it doesn't spell them.
    text = _CUE_RE.sub("", text).strip()
    if not text:
        return
    for _gs, _ps, audio in kokoro_pipeline()(text, voice=voice, speed=speed):
        if audio is None:
            continue
        if isinstance(audio, torch.Tensor):
            audio = audio.detach().cpu().numpy()
        yield _to_pcm16(np.asarray(audio, dtype=np.float32))


# ───────────────────────────── Orpheus ────────────────────────────
# The Orpheus LLM (a Q4 GGUF on a llama.cpp server) is driven ONLY by the
# brain's text — it never authors content. It emits audio tokens rendered as
# "<custom_token_N>"; we map each to a SNAC code, decode frames as they arrive
# and stream PCM. First audio lands in a few hundred ms; a sliding 4-frame
# window joins frames without clicks.

_ORPHEUS_VOICES = {"tara", "leah", "jess", "leo", "dan", "mia", "zac", "zoe"}
_SOS, _EOT, _EOA = 128259, 128009, 128260  # Orpheus prompt framing tokens
_CUSTOM_RE = re.compile(r"<custom_token_(\d+)>")


def snac_model():
    global _snac_model
    if _snac_model is None:
        from snac import SNAC
        log.info("loading SNAC decoder on %s", DEVICE)
        _snac_model = SNAC.from_pretrained("hubertsiuzdak/snac_24khz").eval().to(DEVICE)
        log.info("SNAC ready")
    return _snac_model


def _snac_decode(codes: list[int], snac):
    """Distribute already-de-offset codes into SNAC's 3 codebooks → waveform."""
    n = len(codes) // 7
    if n == 0:
        return None
    l1, l2, l3 = [], [], []
    for j in range(n):
        f = codes[7 * j: 7 * j + 7]
        l1.append(f[0])
        l2.append(f[1]); l2.append(f[4])
        l3.append(f[2]); l3.append(f[3]); l3.append(f[5]); l3.append(f[6])
    dev = next(snac.parameters()).device
    cc = [
        torch.tensor(l1, device=dev).unsqueeze(0),
        torch.tensor(l2, device=dev).unsqueeze(0),
        torch.tensor(l3, device=dev).unsqueeze(0),
    ]
    for c in cc:  # guard a garbled/truncated tail
        c.clamp_(0, 4095)
    with torch.inference_mode():
        audio = snac.decode(cc)
    return audio.squeeze().detach().cpu().numpy().astype(np.float32)


def _orpheus_token_numbers(text: str, voice: str):
    """
    Yield the integer N of each <custom_token_N> as the llama.cpp server streams
    them. Builds Orpheus's framed prompt via the server's /tokenize endpoint so
    the BOS/voice framing matches training exactly.
    """
    body = json.dumps({"content": f"{voice}: {text.strip()}", "add_special": True}).encode()
    req = urllib.request.Request(
        f"{ORPHEUS_URL}/tokenize", data=body, headers={"content-type": "application/json"}
    )
    text_ids = json.load(urllib.request.urlopen(req, timeout=30))["tokens"]
    prompt_ids = [_SOS] + text_ids + [_EOT, _EOA]

    payload = json.dumps({
        "prompt": prompt_ids,
        "n_predict": ORPHEUS_MAX_TOKENS,
        "temperature": 0.6,
        "top_p": 0.95,
        "repeat_penalty": 1.1,
        "stream": True,
        "cache_prompt": False,
    }).encode()
    req = urllib.request.Request(
        f"{ORPHEUS_URL}/completion", data=payload, headers={"content-type": "application/json"}
    )
    resp = urllib.request.urlopen(req, timeout=120)
    buf = ""
    for raw in resp:                       # SSE: one "data: {json}" per line
        line = raw.decode("utf-8", "ignore").strip()
        if not line.startswith("data:"):
            continue
        try:
            ev = json.loads(line[5:].strip())
        except Exception:  # noqa: BLE001
            continue
        buf += ev.get("content", "")
        # Emit complete tokens; keep any partial "<custom_token_…" tail buffered.
        last = 0
        for m in _CUSTOM_RE.finditer(buf):
            yield int(m.group(1))
            last = m.end()
        buf = buf[last:]
        if len(buf) > 64:                  # no partial token is ever this long
            buf = buf[-32:]
        if ev.get("stop"):
            break


def orpheus_stream(text: str, voice: str, speed: float):
    """Stream PCM for one sentence: llama.cpp generates audio tokens, SNAC
    decodes each new frame the moment it lands."""
    snac = snac_model()
    if voice not in _ORPHEUS_VOICES:
        voice = "tara"

    codes: list[int] = []
    n = 0
    first = True
    for num in _orpheus_token_numbers(text, voice):
        # N → SNAC code, removing the per-position (index % 7) bank offset.
        code = num - 10 - ((n % 7) * 4096)
        if code < 0 or code > 4095:        # not an audio code (stray token)
            continue
        codes.append(code)
        n += 1
        if n % 7 == 0 and n >= 28:
            audio = _snac_decode(codes[-28:], snac)
            if audio is None or audio.size < 4096:
                continue
            if first:
                first = False
                yield _to_pcm16(audio[:4096])      # frames 0-1 (head)
            else:
                yield _to_pcm16(audio[2048:4096])  # next frame
    if not first and len(codes) >= 28:             # tail
        audio = _snac_decode(codes[-28:], snac)
        if audio is not None and audio.size >= 8192:
            yield _to_pcm16(audio[4096:8192])


# ───────────────────────────── shared ─────────────────────────────

class TtsRequest(BaseModel):
    text: str
    voice: str | None = None
    speed: float = 1.0


def _to_pcm16(audio: np.ndarray) -> bytes:
    clipped = np.clip(audio, -1.0, 1.0)
    return (clipped * 32767.0).astype("<i2").tobytes()


def _warm():
    try:
        if _engine == "orpheus":
            snac_model()  # preload the decoder regardless of llama-server state
            for _ in orpheus_stream("hello", DEFAULT_VOICE, 1.0):
                break
        else:
            for _ in kokoro_pipeline()("warming up", voice=DEFAULT_VOICE):
                break
    except Exception as e:  # noqa: BLE001
        log.warning("warm-up skipped: %s", e)


@app.get("/health")
def health():
    return JSONResponse(
        {
            "ok": True,
            "engine": _engine,
            "sample_rate": SAMPLE_RATE,
            "device": DEVICE,
            "voice": DEFAULT_VOICE,
        }
    )


@app.post("/tts")
def tts(req: TtsRequest):
    text = (req.text or "").strip()
    voice = req.voice or DEFAULT_VOICE
    if not text:
        return JSONResponse({"error": "empty text"}, status_code=400)

    def gen():
        try:
            stream = orpheus_stream if _engine == "orpheus" else kokoro_stream
            for chunk in stream(text, voice, req.speed):
                if chunk:
                    yield chunk
        except Exception as e:  # surface synthesis errors in the log
            log.exception("tts synthesis failed: %s", e)
            raise

    return StreamingResponse(
        gen(),
        media_type="application/octet-stream",
        headers={"X-Sample-Rate": str(SAMPLE_RATE), "Cache-Control": "no-store"},
    )


if __name__ == "__main__":
    import uvicorn

    port = int(os.environ.get("RAK00N_TTS_PORT", "8991"))
    log.info("TTS engine: %s (voice=%s)", _engine, DEFAULT_VOICE)
    if os.environ.get("RAK00N_TTS_WARM", "1") == "1":
        _warm()
    uvicorn.run(app, host="0.0.0.0", port=port, log_level="info")
