import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs'
import { join, resolve } from 'path'
import { spawnSync } from 'child_process'

const ROOT = resolve(new URL('..', import.meta.url).pathname)
const DIST_DIR = join(ROOT, 'dist', 'installers')
const ENV_FILE = process.env.RAK00N_INSTALLER_ENV_FILE
  ? resolve(process.env.RAK00N_INSTALLER_ENV_FILE)
  : join(ROOT, 'installer', 'managed-endpoints.env')

function fail(message: string): never {
  console.error(`Error: ${message}`)
  process.exit(1)
}

function run(command: string, args: string[], extraEnv?: Record<string, string>): void {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    stdio: 'inherit',
    env: {
      ...process.env,
      ...extraEnv,
    },
  })

  if (result.status !== 0) {
    fail(`${command} ${args.join(' ')} failed with exit code ${result.status ?? 1}`)
  }
}

function parseEnvFile(filePath: string): Record<string, string> {
  const envVars: Record<string, string> = {}
  if (!existsSync(filePath)) {
    return envVars
  }

  const content = readFileSync(filePath, 'utf8')
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    const idx = line.indexOf('=')
    if (idx <= 0) continue

    const key = line.slice(0, idx).trim()
    let value = line.slice(idx + 1).trim()

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    envVars[key] = value
  }

  return envVars
}

function requireEnv(name: string): string {
  const value = process.env[name]?.trim()
  if (!value) {
    fail(`${name} is required. Put it in ${ENV_FILE} or export it in your shell.`)
  }
  return value
}

function generateInstallerPayload(): void {
  const cliPath = join(ROOT, 'dist', 'cli.mjs')
  if (!existsSync(cliPath)) {
    fail('dist/cli.mjs not found. Run bun run build first.')
  }

  const cliSource = readFileSync(cliPath, 'utf8')
  const cliBase64 = Buffer.from(cliSource, 'utf8').toString('base64')

  const payloadPath = join(ROOT, 'installer', 'payload.generated.ts')
  const payload = `/**\n * AUTO-GENERATED by scripts/build-installers.ts — DO NOT EDIT\n * Contains the embedded CLI payload used by installer/index.ts.\n */\n\nexport const EMBEDDED_CLI_MJS_BASE64 = ${JSON.stringify(cliBase64)} as const\n`

  writeFileSync(payloadPath, payload, 'utf8')
  console.log(`✓ Generated installer payload: ${payloadPath}`)
}

function main(): void {
  const fromFile = parseEnvFile(ENV_FILE)
  for (const [key, value] of Object.entries(fromFile)) {
    process.env[key] ??= value
  }

  const buildSecret = process.env.RAK00N_BUILD_SECRET?.trim() ?? ''
  const hasCredentials = !!(
    buildSecret &&
    process.env.RAK00N_MANAGED_KEY_1?.trim() &&
    process.env.RAK00N_MANAGED_ENDPOINT_1?.trim() &&
    process.env.RAK00N_MANAGED_MODEL_1?.trim()
  )

  if (!hasCredentials) {
    console.log('No managed credentials found — building installer without credential provisioning.')
    console.log('The CLI will fall back to local Ollama or manual provider configuration.\n')
  } else {
    console.log(`Using installer env file: ${existsSync(ENV_FILE) ? ENV_FILE : '(none found, using shell env only)'}`)
  }

  run('bun', ['run', 'build'])

  if (hasCredentials) {
    run('bun', ['run', 'build:credentials'])
  } else {
    // Write empty credentials stub so the installer compiles
    const stubPath = join(ROOT, 'installer', 'credentials.enc.ts')
    writeFileSync(stubPath, `export const ENCRYPTED_CREDENTIALS = '' as const\nexport const CREDENTIAL_SLOT_COUNT = 0 as const\nexport const BUILD_TIME = '${new Date().toISOString()}' as const\n`, 'utf8')
    console.log('✓ Generated empty credentials stub (no-credential build)')
  }

  generateInstallerPayload()

  mkdirSync(DIST_DIR, { recursive: true })

  const macTarget = process.env.RAK00N_INSTALLER_MAC_TARGET ?? 'bun-darwin-arm64'
  const winTarget = process.env.RAK00N_INSTALLER_WINDOWS_TARGET ?? 'bun-windows-x64'

  const defineSecret = buildSecret
    ? `RAK00N_BUILD_SECRET_DEFINE=${JSON.stringify(buildSecret)}`
    : `RAK00N_BUILD_SECRET_DEFINE=${JSON.stringify('')}`

  run('bun', [
    'build',
    '--compile',
    '--target',
    macTarget,
    '--define',
    defineSecret,
    'installer/index.ts',
    '--outfile',
    'dist/installers/rak00n-installer-macos',
  ])

  run('bun', [
    'build',
    '--compile',
    '--target',
    winTarget,
    '--define',
    defineSecret,
    'installer/index.ts',
    '--outfile',
    'dist/installers/rak00n-installer-windows.exe',
  ])

  // Re-sign macOS binary — Bun's --compile produces a malformed Mach-O
  // signature that macOS Gatekeeper rejects. Strip it and ad-hoc sign so
  // the binary runs without manual codesign intervention.
  if (process.platform === 'darwin') {
    const macBinary = join(DIST_DIR, 'rak00n-installer-macos')
    run('codesign', ['--remove-signature', macBinary])
    run('codesign', ['--force', '--sign', '-', macBinary])
    console.log('✓ macOS binary re-signed (ad-hoc)')
  }

  console.log('')
  console.log('✓ Installers built:')
  console.log('  - dist/installers/rak00n-installer-macos')
  console.log('  - dist/installers/rak00n-installer-windows.exe')
}

main()
