/**
 * Build-time credential encryption script.
 *
 * Reads managed provider credentials from env vars, encrypts them with
 * AES-256-GCM, and writes the encrypted blob to installer/credentials.enc.ts.
 * The installer binary decrypts and writes to the OS keychain at install time.
 *
 * Usage:
 *   cp installer/managed-endpoints.env.example installer/managed-endpoints.env
 *   # Fill installer/managed-endpoints.env
 *   bun run scripts/build-credentials.ts
 *
 * The output file (installer/credentials.enc.ts) must be treated as sensitive
 * even though keys are encrypted — it should NOT be committed to source control.
 * It is listed in .gitignore.
 *
 * The RAK00N_BUILD_SECRET must be the same value that is embedded in the installer
 * binary at build time. Store it in your CI/CD secrets vault.
 */

import { createCipheriv, createHash, randomBytes } from 'crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const ROOT = new URL('..', import.meta.url).pathname

const installerEnvPath = join(ROOT, 'installer', 'managed-endpoints.env')
if (existsSync(installerEnvPath)) {
  const raw = readFileSync(installerEnvPath, 'utf8')
  for (const rawLine of raw.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue

    const idx = line.indexOf('=')
    if (idx <= 0) continue

    const key = line.slice(0, idx).trim()
    let value = line.slice(idx + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    process.env[key] ??= value
  }
}

// ─── Derive encryption key ────────────────────────────────────────────────────

const BUILD_SECRET = process.env.RAK00N_BUILD_SECRET
if (!BUILD_SECRET) {
  console.error('Error: RAK00N_BUILD_SECRET env var is required')
  process.exit(1)
}

// 32-byte key = SHA-256(buildSecret + appSalt)
// The appSalt is public (in source) — provides domain separation between
// different RAK00N builds. The buildSecret is the actual secret.
const APP_SALT = 'rak00n.managed.credentials.v1'
const encryptionKey = createHash('sha256')
  .update(BUILD_SECRET + APP_SALT)
  .digest()

// ─── Collect credentials ──────────────────────────────────────────────────────

interface SlotData {
  slot: string
  apiKey: string
  endpoint: string
  model: string
  label: string
}

const slots: SlotData[] = []

for (const n of [1, 2, 3]) {
  const apiKey = process.env[`RAK00N_MANAGED_KEY_${n}`]
  const endpoint = process.env[`RAK00N_MANAGED_ENDPOINT_${n}`]
  const model = process.env[`RAK00N_MANAGED_MODEL_${n}`]
  const label = process.env[`RAK00N_MANAGED_LABEL_${n}`]

  if (!apiKey || !endpoint || !model) {
    console.warn(`Warning: slot ${n} incomplete — skipping (set RAK00N_MANAGED_KEY_${n}, RAK00N_MANAGED_ENDPOINT_${n}, RAK00N_MANAGED_MODEL_${n})`)
    continue
  }

  slots.push({
    slot: `managed.${n}`,
    apiKey,
    endpoint,
    model,
    label: label ?? `RAK00N Managed ${n}`,
  })
}

if (slots.length === 0) {
  console.error('Error: no complete credential slots found. Provide at least RAK00N_MANAGED_KEY_1, RAK00N_MANAGED_ENDPOINT_1, RAK00N_MANAGED_MODEL_1')
  process.exit(1)
}

// ─── Encrypt ──────────────────────────────────────────────────────────────────

const plaintext = JSON.stringify(slots)
const iv = randomBytes(12) // 96-bit IV for GCM
const cipher = createCipheriv('aes-256-gcm', encryptionKey, iv)
const ciphertext = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()])
const authTag = cipher.getAuthTag()

const blob = {
  version: 1,
  iv: iv.toString('base64'),
  authTag: authTag.toString('base64'),
  ciphertext: ciphertext.toString('base64'),
  buildTime: new Date().toISOString(),
  slotCount: slots.length,
}

// ─── Write output ─────────────────────────────────────────────────────────────

const outDir = join(ROOT, 'installer')
mkdirSync(outDir, { recursive: true })
const outPath = join(outDir, 'credentials.enc.ts')

const outContent = `/**
 * AUTO-GENERATED by scripts/build-credentials.ts — DO NOT EDIT
 * Contains AES-256-GCM encrypted managed provider credentials.
 * This file must NOT be committed to source control.
 * Gitignored via root .gitignore
 */

// Encrypted credential blob — decrypt with installer/index.ts
export const ENCRYPTED_CREDENTIALS = ${JSON.stringify(JSON.stringify(blob))} as const

export const CREDENTIAL_SLOT_COUNT = ${slots.length} as const
export const BUILD_TIME = '${blob.buildTime}' as const
`

writeFileSync(outPath, outContent, 'utf8')

console.log(`✓ Encrypted ${slots.length} credential slot(s) → ${outPath}`)
console.log(`  Build time: ${blob.buildTime}`)
console.log(`  Slots: ${slots.map(s => s.slot).join(', ')}`)
console.log('')
console.log('Next steps:')
console.log('  1. bun run build:installers  — compile macOS and Windows installers')
console.log('  2. Distribute the compiled installer (never distribute credentials.enc.ts itself)')
